services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfiles/orchestra/Dockerfile
    container_name: orchestra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srcs/CLI:/app
    ports:
      - "5042:5042"
    env_file: .env
    networks:
      - monitoring
    restart: on-failure

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    env_file: .env
    networks:
      - monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge